# Generated by Django 5.1.3 on 2025-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20, verbose_name="نام")),
                ("lname", models.CharField(max_length=20, verbose_name="نام خانوادگی")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("message", models.CharField(max_length=500, verbose_name="متن پیام")),
            ],
            options={
                "verbose_name": "نامه",
                "verbose_name_plural": "نامه ها",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربران"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("seller", "فروشنده"), ("customer", "مشتری")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
