# Generated by Django 5.1.3 on 2025-01-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_subtitles",
        ),
    ]
