# Generated by Django 5.1.3 on 2025-07-01 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_coursefeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefeedback",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                verbose_name="امتیاز",
            ),
        ),
    ]
