# Generated by Django 5.1.3 on 2025-01-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_remove_course_course_subtitles"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="img",
            field=models.ImageField(null=True, upload_to="photo"),
        ),
    ]
