# Generated by Django 5.1.3 on 2025-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_coursefeedback_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefeedback",
            name="name",
            field=models.CharField(max_length=50, verbose_name="نام"),
        ),
    ]
