# Generated by Django 5.1.3 on 2025-01-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_course_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="img",
            new_name="course_img",
        ),
    ]
