# Generated by Django 5.1.3 on 2025-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_rename_img_course_course_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_descreption",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_title",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
