# Generated by Django 5.1.3 on 2025-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_coursefeedback_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="امتیاز",
            ),
        ),
    ]
