# Generated by Django 5.1.3 on 2025-01-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_course_course_descreption_course_course_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_price",
            new_name="course_price_1",
        ),
        migrations.AddField(
            model_name="course",
            name="course_price_2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
