# Generated by Django 5.1.3 on 2025-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_rename_course_price_course_course_price_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_price_1",
            new_name="course_discount_price",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_price_2",
            new_name="course_price",
        ),
    ]
