# Generated by Django 5.1.3 on 2025-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0008_rename_course_price_1_course_course_discount_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_level",
            field=models.CharField(
                help_text="سطح دوره را مشخص کنید", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="course_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_situation",
            field=models.CharField(
                choices=[
                    ("1", "در انتظار برگزاری"),
                    ("2", "در حال برگزاری"),
                    ("3", "به اتمام رسیده"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="course_teacher",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
