# Generated by Django 5.1.3 on 2025-07-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_alter_coursefeedback_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefeedback",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="main_app.product",
                verbose_name="محصول",
            ),
        ),
    ]
