# Generated by Django 5.1.3 on 2025-04-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_rename_descreption_blog_blog_descreption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="نام کتاب")),
                ("descreption", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="عنوان فصل")),
                ("order", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="پایه")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="عنوان درس")),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SampleQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="sample_questions/")),
                ("is_full_book", models.BooleanField(default=False)),
                (
                    "Chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_file", models.FileField(blank=True, upload_to="videos/")),
                ("is_free", models.BooleanField(default=False)),
                ("descreption", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="course",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_descreption",
            new_name="descreption",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_img",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="book",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.grade"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="Book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.book"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="Chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.chapter"
            ),
        ),
        migrations.AddField(
            model_name="samplequestions",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.book"
            ),
        ),
        migrations.AddField(
            model_name="videos",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.lesson",
            ),
        ),
    ]
