# Generated by Django 5.1.3 on 2025-07-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_alter_coursefeedback_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="main_app.grade",
                verbose_name="پایه",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="main_app.product",
                verbose_name="محصول مرتبط",
            ),
        ),
    ]
