# Generated by Django 5.1.3 on 2025-07-06 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_alter_book_grade_alter_video_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lname", models.CharField(max_length=20, verbose_name="نام")),
                ("fname", models.CharField(max_length=20, verbose_name="نام خانوادگی")),
                (
                    "phone",
                    models.IntegerField(max_length=11, verbose_name="شماره تماس"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "subject",
                    models.CharField(max_length=50, verbose_name="عنوان آموزش"),
                ),
                (
                    "options",
                    models.CharField(
                        choices=[
                            ("1", "تدریس ریاضیات متوسطه اول"),
                            ("2", "تدریس ریاضیات متوسطه دوم"),
                        ],
                        default="1",
                        max_length=30,
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="لینک نمونه"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": " دبیر",
                "verbose_name_plural": "دبیران ",
            },
        ),
    ]
