# Generated by Django 5.1.3 on 2025-04-28 08:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_book_chapter_grade_lesson_samplequestions_videos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="lesson",
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "verbose_name": "کتاب",
                "verbose_name_plural": "کتاب\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["order"],
                "verbose_name": "فصل",
                "verbose_name_plural": "فصل\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["id"],
                "verbose_name": "پایه",
                "verbose_name_plural": "پایه\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "درس",
                "verbose_name_plural": "درس\u200cها",
            },
        ),
        migrations.RemoveField(
            model_name="blog",
            name="descreption",
        ),
        migrations.RemoveField(
            model_name="book",
            name="descreption",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="Book",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="Chapter",
        ),
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.TextField(
                default="مقاله ریاضی", null=True, verbose_name="توضیحات مقاله"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(
                max_length=500, null=True, verbose_name="توضیحات کتاب"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="عکس مقاله"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان مقاله"),
        ),
        migrations.AlterField(
            model_name="book",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.grade",
                verbose_name="پایه",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, verbose_name="نام کتاب"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.book",
                verbose_name="کتاب",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="order",
            field=models.PositiveIntegerField(verbose_name="ترتیب فصل"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان فصل"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(verbose_name="ترتیب درس"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان درس"),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان محصول")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت (تومان)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال؟")),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("full", "کل کتاب"),
                            ("chapter", "فصل خاص"),
                            ("summary", "جمع\u200cبندی"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="نوع محصول",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات محصول"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.chapter",
                        verbose_name="فصل",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SampleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان سوال")),
                (
                    "file",
                    models.FileField(
                        upload_to="sample_questions",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="فایل سوال",
                    ),
                ),
                (
                    "is_full_book",
                    models.BooleanField(
                        default=False, verbose_name="برای کل کتاب است؟"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.chapter",
                        verbose_name="فصل",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه سوال",
                "verbose_name_plural": "نمونه سوالات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان ویدئو")),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        upload_to="videos",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mov", "avi"]
                            )
                        ],
                        verbose_name="فایل ویدئو",
                    ),
                ),
                (
                    "purchase_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک خرید (اسپات پلیر)"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="رایگان است؟"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات ویدئو"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.lesson",
                        verbose_name="درس مربوطه",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.product",
                        verbose_name="محصول مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدئو",
                "verbose_name_plural": "ویدئوها",
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="SampleQuestions",
        ),
        migrations.DeleteModel(
            name="videos",
        ),
        migrations.AddField(
            model_name="lesson",
            name="chapter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.chapter",
                verbose_name="فصل",
            ),
        ),
    ]
