# Generated by Django 5.1.3 on 2025-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_remove_videos_lesson_alter_blog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["book"],
                "verbose_name": "فصل",
                "verbose_name_plural": "فصل\u200cها",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photo", verbose_name="تصویر محصول"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photo", verbose_name="عکس مقاله"
            ),
        ),
    ]
