# Generated by Django 5.1.3 on 2025-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_teachercontact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teachercontact",
            options={"verbose_name": " مدرس", "verbose_name_plural": "مدرسان "},
        ),
        migrations.AlterField(
            model_name="teachercontact",
            name="fname",
            field=models.CharField(max_length=20, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="teachercontact",
            name="lname",
            field=models.CharField(max_length=20, verbose_name="نام خانوادگی"),
        ),
    ]
