# Generated by Django 5.1.3 on 2025-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_alter_chapter_options_product_image_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="عکس مقاله"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="تصویر محصول"
            ),
        ),
    ]
