# Generated by Django 5.1.3 on 2025-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_alter_teachercontact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachercontact",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="شماره تماس"),
        ),
    ]
