# Generated by Django 5.1.3 on 2025-04-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_alter_blog_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["title"],
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.AlterModelOptions(
            name="samplequestion",
            options={
                "verbose_name": "نمونه سوال",
                "verbose_name_plural": "نمونه سوالات",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["title"],
                "verbose_name": "ویدئو",
                "verbose_name_plural": "ویدئوها",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="samplequestion",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="video",
            name="created_at",
        ),
    ]
