# Generated by Django 5.1.3 on 2025-07-21 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0015_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price_paid",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("cart", "سبدخرید"), ("final", "سفارش نهایی")],
                default="cart",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="Orderitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qnt", models.PositiveIntegerField(default=0)),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="main_app.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
        ),
    ]
