# Generated by Django 5.1.3 on 2025-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0015_alter_product_options_alter_samplequestion_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Logomath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="عنوان لوگو")),
                (
                    "image",
                    models.ImageField(upload_to="photos", verbose_name="عکس لوگو"),
                ),
            ],
            options={
                "verbose_name": "لوگو",
                "verbose_name_plural": "لوگو ها",
            },
        ),
    ]
