# Generated by Django 5.1.3 on 2025-04-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_logomath"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Logomath",
        ),
    ]
