# Generated by Django 5.1.3 on 2025-07-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_rename_price_paid_order_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["order"],
                "verbose_name": "ریز سفارش",
                "verbose_name_plural": "ریز سفارش ها",
            },
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="Order",
            new_name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="qnt",
        ),
    ]
