# Generated by Django 5.1.3 on 2025-06-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0017_delete_logomath"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="قیمت  با تخفیف (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="teacher",
            field=models.CharField(max_length=150, null=True, verbose_name="مدرس"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="main_app.book",
                verbose_name="کتاب",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                choices=[("1", "فعال"), ("2", "غیرفعال")],
                default="1",
                verbose_name="وضعیت دوره",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="قیمت (تومان)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("1", "کل کتاب"), ("2", "یک فصل کتاب"), ("3", "جمع بندی")],
                default="1",
                max_length=10,
                verbose_name="نوع محصول",
            ),
        ),
    ]
