# Generated by Django 5.1.3 on 2025-07-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0017_alter_orderitem_options_rename_order_orderitem_order_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
