# Generated by Django 5.1.3 on 2025-07-23 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_remove_order_price_remove_order_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name=" عنوان تیکت")),
                ("message", models.CharField(max_length=500, verbose_name="متن تیکت")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
    ]
