# Generated by Django 5.1.3 on 2025-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_product_discount_price_product_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="قیمت  با تخفیف (تومان)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("3", "کل کتاب"), ("4", "یک فصل کتاب"), ("5", "جمع بندی")],
                default="3",
                max_length=10,
                verbose_name="نوع محصول",
            ),
        ),
    ]
