# Generated by Django 5.1.3 on 2025-06-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_alter_product_discount_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.CharField(
                choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                default="active",
                max_length=10,
                verbose_name="وضعیت دوره",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("full", "کل کتاب"),
                    ("part", "یک فصل کتاب"),
                    ("summary", "جمع بندی"),
                ],
                default="full",
                max_length=10,
                verbose_name="نوع محصول",
            ),
        ),
    ]
