# Generated by Django 5.1.3 on 2025-07-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="title",
            new_name="subject",
        ),
    ]
